# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fabric',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
