# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0002_auto_20160607_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='sku',
            field=models.IntegerField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='type',
            field=models.CharField(choices=[('C', 'Cotton'), ('W', 'Wool'), ('L', 'Linen')], default='C', max_length=1),
        ),
    ]
