# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0003_auto_20160614_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='height_field',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='width_field',
            field=models.IntegerField(default=400),
        ),
    ]
