# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import tailors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tailors.models.upload_location, width_field='width_field')),
                ('color', models.CharField(max_length=120)),
                ('sku', models.IntegerField(max_length=8)),
                ('type', models.CharField(choices=[('C', 'Cotton'), ('W', 'Wool')], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tailor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=tailors.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
