# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0002_delete_fabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailorID', models.CharField(max_length=120)),
                ('fabricID', models.CharField(max_length=120)),
            ],
        ),
    ]
