# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 05:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fabrics', '0002_auto_20160607_0948'),
        ('tailors', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tailor',
            name='fabric_invetory',
            field=models.ManyToManyField(blank=True, to='fabrics.Fabric'),
        ),
        migrations.AddField(
            model_name='tailor',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='manager_sellers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tailor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
