# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0004_auto_20160607_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailor',
            old_name='fabric_invetory',
            new_name='fabric_inventory',
        ),
    ]
