# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0005_auto_20160608_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='managers',
        ),
    ]
