# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_fabrics'),
        ('tailors', '0006_remove_tailor_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='orders',
            field=models.ManyToManyField(blank=True, to='shop.OrderItem'),
        ),
    ]
