# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0011_auto_20160615_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='orders',
        ),
    ]
