# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_fabrics'),
        ('tailors', '0013_tailor_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailor',
            name='test',
        ),
        migrations.AddField(
            model_name='tailor',
            name='tailor_orders',
            field=models.ManyToManyField(blank=True, to='shop.OrderItem'),
        ),
    ]
