# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0014_auto_20160615_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='tailor_orders',
            field=models.ManyToManyField(blank=True, to='shop.Order'),
        ),
    ]
