# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0015_auto_20160615_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='height_field',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='width_field',
            field=models.IntegerField(default=400),
        ),
    ]
