# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20160601_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='special',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='option3',
        ),
        migrations.AlterField(
            model_name='productoption',
            name='type',
            field=models.IntegerField(choices=[(1, 'Size'), (2, 'Colour')], verbose_name='Type'),
        ),
    ]
