# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160602_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='back_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Back Width'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='bicep_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Bicep'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='crotch_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Crotch'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='front_chest_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Front Chest Width'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='front_jacket_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Front Jacket Length'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='full_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Full Back Length'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='full_chest_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Full Chest'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='full_shoulder_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Full Shoulder Width'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='half_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Half Back Length'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='half_shoulder_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Half Shoulder Width'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='hip_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Hips/Seat'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='knee_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Knee'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='left_full_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Left Full Sleeve'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='left_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Left Sleeve'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='neck_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Neck Size'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='right_full_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Right Full Sleeve'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='right_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Right Sleeve'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='thigh_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Thigh'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='trouser_inseam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Trouser Inseam'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='trouser_outseam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Trouser Outseam'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='trouser_waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Trouser Waist'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='waist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Waist/Stomach'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='wrist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Wrist Size'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='back_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Back Width'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bicep_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Bicep'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='crotch_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Crotch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='front_chest_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Front Chest Width'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='front_jacket_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Front Jacket Length'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='full_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Full Back Length'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='full_chest_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Full Chest'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='full_shoulder_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Full Shoulder Width'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='half_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Half Back Length'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='half_shoulder_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Half Shoulder Width'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='hip_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Hips/Seat'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='knee_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Knee'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='left_full_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Left Full Sleeve'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='left_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Left Sleeve'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='neck_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Neck Size'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='right_full_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Right Full Sleeve'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='right_sleeve',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Right Sleeve'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='thigh_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Thigh'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='trouser_inseam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Trouser Inseam'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='trouser_outseam',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Trouser Outseam'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='trouser_waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Trouser Waist'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='waist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Waist/Stomach'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='wrist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Wrist'),
        ),
    ]
