# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0003_auto_20160614_0030'),
        ('shop', '0010_auto_20160614_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(blank=True, to='fabrics.Fabric'),
        ),
    ]
