# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics', '0003_auto_20160614_0030'),
        ('shop', '0011_product_fabrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='fabrics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fabrics.Fabric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabrics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fabrics.Fabric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(to='fabrics.Fabric'),
        ),
    ]
