# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20160616_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabrics',
            field=models.ManyToManyField(to='fabrics.Fabric'),
        ),
    ]
