# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20160616_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='back_width',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='bicep_size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='front_chest_width',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='front_jacket_length',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='full_chest_size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='half_shoulder_width',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='knee_size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='left_full_sleeve',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='left_sleeve',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='right_full_sleeve',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='right_sleeve',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='thigh_size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='trouser_inseam',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='trouser_outseam',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='trouser_waist',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='back_width',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='bicep_size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='front_chest_width',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='front_jacket_length',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='full_chest_size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='half_shoulder_width',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='knee_size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='left_full_sleeve',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='left_sleeve',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='right_full_sleeve',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='right_sleeve',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='thigh_size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='trouser_inseam',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='trouser_outseam',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='trouser_waist',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='chest_around',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Chest Around'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='pants_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Pants Length'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Sleeve Length'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='stomach',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Stomach'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='chest_around',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Chest Around'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pants_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Pants Length'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Sleeve Length'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stomach',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Stomach'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='crotch_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Rise/Crotch'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='crotch_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Rise/Crotch'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wrist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Wrist Size'),
        ),
    ]
