# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20160619_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='chest_around',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chest Around'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='crotch_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rise/Crotch'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='full_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Full Back Length'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='full_shoulder_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Full Shoulder Width'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='half_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Half Back Length'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='hip_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hips/Seat'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='neck_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Neck Size'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='pants_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pants Length'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sleeve Length'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='stomach',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stomach'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='waist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waist/Stomach'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='wrist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wrist Size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='chest_around',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Chest Around'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='crotch_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Rise/Crotch'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='full_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Full Back Length'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='full_shoulder_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Full Shoulder Width'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='half_back_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Half Back Length'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='hip_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hips/Seat'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='neck_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Neck Size'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pants_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pants Length'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sleeve_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sleeve Length'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stomach',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Stomach'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='waist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waist/Stomach'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wrist_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Wrist Size'),
        ),
    ]
